// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sample_int_crank
IntegerVector sample_int_crank(int n, int size, NumericVector prob);
RcppExport SEXP wrswoR_sample_int_crank(SEXP nSEXP, SEXP sizeSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    int n = Rcpp::as<int >(nSEXP);
    int size = Rcpp::as<int >(sizeSEXP);
    NumericVector prob = Rcpp::as<NumericVector >(probSEXP);
    IntegerVector __result = sample_int_crank(n, size, prob);
    return Rcpp::wrap(__result);
END_RCPP
}
