# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample.int.crank <- function(n, size, prob) {
    .Call('wrswoR_sample_int_crank', PACKAGE = 'wrswoR', n, size, prob)
}

