# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp::loadModule("wrswoR_RcppExports", 
    what = c("rcpp_hello_world",
             "sample.int.crank"))
